### ISSUE TITLE
Encrypted text

### ISSUE THREAD

**Issue by delirious44** [deatcoca/Corbeau#5]
The first time you enter in the website, you write the text you want to encrypt and then push the button encrypt, the encryption works but the encrypted text in the textarea box stays for just few seconds and then disappears from the box.. This happens only the first time you encrypt the message, then It works fine. I thought it is something you want to know.

**Comment by deatcoca** [comment]
Do you encounter this problem with the Caesar Cipher or the Vigenere Cipher ?  And what do you mean by the first time, the first time _ever_ or just at the beginning when you enter the website ? 
I connected to the website with TOR to be sure it simulate a "first time" connection and I didn't encounter this issue. I am making modification on the server at the moment, so that may have caused what you encountered :thinking: 

Thank you for opening an issue! If you come across this bug again please tell me here.

**Comment by delirious44** [comment]
The bug is actually real, and it happens everytime you load the website, the reason it happens is that in index.html you have the from action set as "<form action="#">" that means that in every submit by any button that is made, the url of your page is going to change from "https://deatcoca.me/Corbeau/", to "https://deatcoca.me/Corbeau/?#", so the form adds "?#" to your url and sort of reloads the page with the new url, after the first time you click on the submit, then this doesnt happen because the url is already "https://deatcoca.me/Corbeau/?#"..
Ive fixed this problem in my fork by modyfing the form action in index.html, and I can make a pull request, but If that is against your contribution.md then I can send you the code which is .. 
instead of "<form action="#">" you do this "<form action="javascript:void(0);">", 

So do I pull request, or you are going to change the index,html ?

**Comment by delirious44** [comment]
The bug is actually real. Everytime you click on the website link and load the website, the url of the website will be https://deatcoca.me/Corbeau/ , however, because the form on index.html is ``` <form action="#"> ```
In any submit button within that form which includes the encrypt button aswell, the form is going to go ahead with the action and change your url from **https://deatcoca.me/Corbeau/** , to **https://deatcoca.me/Corbeau/?#** , notice the **?#** added because of the form action, so this is going to make your website reload and the encrypted text go away. The reason this doesnt happen after the first time is that the url is now already **https://deatcoca.me/Corbeau/?#**, so it wont reload again and miss your encrypted message.

Removing the action attribute in the form and leaving it like this ```<form>``` might seem like a good idea but it doesnt work in every browser because in some browsers the form itself changes the url without even the action attribute.. so I changed the action attribute to ```<form action="javascript:void(0);"``` , and this prevents the form from behaving like that..

I can make a pull request, but I dont know if that is according to your contributing.md  ?

**Comment by deatcoca** [comment]
It seems logical indeed, but I really never encountered this bug before, I only use Firefox though.
Thank you very much for pointing this out, your pull request is conform to the contributing.md and everything seems to work fine, so I will merge.
Again thank you very much for contributing to this project ! It's very motivating :smile:

**Comment by delirious44** [comment]
Sometimes when browsers are involved in behaviours then it gets a bit messy. But from what I know forms seem a bit weird, so you gotta keep an eye on them. 
Its cool, as I said, I will look out for your project and try and help as much as I can 😉
