### ISSUE TITLE
Expend the Toolbox size

### ISSUE THREAD

**Issue by deatcoca** [deatcoca/Corbeau#7]
Depending on the button's style, it doesn't always render nicely. (This is just a reminder for me as I can't fix it right now)
![2017-03-28 14_39_50-caesar cipher encryption](https://cloud.githubusercontent.com/assets/24621065/24405324/c3edf5d8-13c4-11e7-99e7-e21ad028b44c.png)

**Comment by delirious44** [comment]
Can you elaborate ? Maybe I can fix it ?

**Comment by deatcoca** [comment]
Thank you @delirious44 but I was just at school and couldn't perform any action on the server so I posted this issue so I would remember to fix it. Nothing really important :)
